# -*- coding: utf-8 -*-
"""Demo-Waste detection 50 epochs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6kKt5loM5KaL60ktNdI0cVp77zNucu2
"""

!nvidia-smi

! pip install ultralytics

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo mode=checks

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="txFChTRTDYrb32KiOz7K")
project = rf.workspace("waste-detection-f8nuy").project("waste-detection-wrre8")
dataset = project.version(1).download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs =50 imgsz=640

Image(filename=f'/content/runs/detect/train2/results.png', width=600)

Image(filename=f'/content/runs/detect/train2/confusion_matrix.png', width=600)

Image(filename=f'/content/runs/detect/train2/labels.jpg', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train2/weights/best.pt data={dataset.location}/data.yaml

#source='/content/Waste-detection-1/test/images'
!yolo task=detect mode=predict model=/content/runs/detect/train2/weights/best.pt conf=0.5 source={dataset.location}/test/images save_txt=true

import glob
from IPython.display import Image, display
for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg'):
  display(Image(filename=image_path,height=600))
  print("\n")